name: Package and Release

on:
  release:
    types: [published]
    tags:
      - 'v*.*.*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install 7-Zip
      run: sudo apt-get install p7zip-full

    - name: Extract Version from Tag
      run: echo "VERSION=${GITHUB_REF##*/}" | sed 's/^v//' >> $GITHUB_ENV

    - name: Zip files
      run: 7z a -tzip -mx=9 ./Build/LethalSDK_Project.zip ./LethalSDK_Project

    - name: Zip files
      run: 7z a -tzip -mx=9 ./Releases/LethalSDK_v${{ env.VERSION }}.zip ./Build/*

    - name: Upload Release Asset Zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.LETHAL_SDK_SECRET }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Releases/LethalSDK_v${{ env.VERSION }}.zip
        asset_name: LethalSDK_v${{ env.VERSION }}.zip
        asset_content_type: application/zip

    - name: 7z files
      run: 7z a -t7z -mx=9 ./Build/LethalSDK_Project.7z ./LethalSDK_Project

    - name: 7z files
      run: 7z a -t7z -mx=9 ./Releases/LethalSDK_v${{ env.VERSION }}.7z ./Build/* -x!LethalSDK_Project.zip

    - name: Upload Release Asset 7z
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.LETHAL_SDK_SECRET }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Releases/LethalSDK_v${{ env.VERSION }}.7z
        asset_name: LethalSDK_v${{ env.VERSION }}.7z
        asset_content_type: application/x-7z-compressed
